apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/cert-manager.yaml
- argocd-applications/certificates.yaml
# Auth
- argocd-applications/dex.yaml
- argocd-applications/external-secrets.yaml
- argocd-applications/oauth2-proxy.yaml
- argocd-applications/oidc-auth.yaml
# Dapr
- argocd-applications/dapr.yaml
# KServe
- argocd-applications/kserve.yaml
# GraphScope
- argocd-applications/graphscope-store.yaml
- argocd-applications/graphscope.yaml
# Istio
- argocd-applications/istio-operator.yaml
- argocd-applications/istio-resources.yaml
- argocd-applications/istio.yaml
- argocd-applications/kiali.yaml
