apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/cert-manager.yaml
# Dapr
- argocd-applications/dapr.yaml
# GraphScope
- argocd-applications/graphscope-store.yaml
- argocd-applications/graphscope.yaml
# Istio
- argocd-applications/istio-operator.yaml
- argocd-applications/istio-resources.yaml
- argocd-applications/istio.yaml
# Kubeflow
- argocd-applications/kubeflow-namespace.yaml
- argocd-applications/kubeflow-roles.yaml
- argocd-applications/kubeflow-pipelines.yaml
- argocd-applications/kubeflow-training-operator.yaml
- argocd-applications/kubeflow-volumes-webapp.yaml
# Sealed Secrets
- argocd-applications/sealed-secrets.yaml
