apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/istio-operator.yaml
# Kubeflow
- argocd-applications/kubeflow-namespace.yaml
- argocd-applications/kubeflow-roles.yaml
- argocd-applications/kubeflow-pipelines.yaml
