apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth
  namespace: auth
  labels:
    app: auth
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /auth
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: dex.auth.svc.cluster.local
        port:
          number: 5556
