kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgC9xEirUZmKu5SqQ3kdPXjN8vjMmu3S0MDFLfF0dHrYcHjeGyWGZnO/abBYowbB10ziQ8JPYUb6YNA4h5akEWldtCZCcs+N6ny1aQmx2sugdL85TURI7R4RdxGckNwkwPt3mPa23BxoZG/rWhGkcght5FxnpvOC4LgdScmq5DOfO86Ad2hCww40MrvpZ6M2EeFjOTsYFs/wdALLDEtrX0jRqM7v7RVwnPZBrMydzLp5nG+Xe0u2MXGu18JXt3XgX42Mu0DYb34dbM7CsEBavkTafmY+yw29f5AgdpPd93afzqHkIeo1pIJ+fCRgiCWoukzCAsGl2r9c5hr/XYCsD2nle/EsWDakEPR2Atl+yCvb23vjG0N6XmTxRiimmlRZCukwdUoOqDtKWKgWcBJ5+y6Nk3+P6aDE/8CiTwhTlZU+gq66Hi9Kznek1pWJA3d3vCFqO1F+SRbR0R3PmEHXoS+l4dVM5DMDei+F4qAcEptXtm6cfos5qySZdMy0QiOPf1LqldOlc9/C5VrCP8XUxEjGp589AShvve3gdDe9Ss2De4O9yMnPF47+GEnCz8+XomeY38bWmoNwnB/8v7OsNi3TigqaQFk/XYQtI0fmLQ2kJlAig7AabQ6IV6KR4UMHE3jlz0akfrDgQPJl0A4Gg6/RB9PvQPAX0bUdD8R9rn9SIY0D+HxjialNXIvNU0RPxP4k+sxWz7NMbl5yVAeW+TQdZchNa8MIWmqSg2Pa5KT8eur8rJTCn8vySYerO0X0OUb7joTSqgNK4EHkH3P2cpBenIMUXG0gAWCMoL6FiTNwLmHHPeaBBSDhmfzKRcf0Nc+kRmRQ4MZIMFW6BclLyN/KKTkGIbnaXz9ZNDyJlgRbCUsDUVhFw9V7d/yo92MaLN27yRAIt2bFd+fZFl0gZTG/Wl1btH/aRGeJ8ds7zcetG2tNscIPjdCB1oIwEB/KmorJei/RSoZed3vKpwYrnIreKJZl6VsNjvt0pAVWOqhi9AXUz4BbCNkSAg+3xuhYLhiTEbHGsS+nI6XR0CyY3cnNk0iSKme8xcshEaOV4hCwVIPgxctLqvYqtcA3DBX+nPwcqrzw78sWWApJYuzkSX6q+hPBwgfGDYpNBSR9wki71hHuchfKtAm+I++y5DpIvCaGEiUxVSIak67b/TgD2xs3wn10f29PQcJrIFH5Qsg/y/SUILg/kI4J+WH6tr5bMG/ahXNBlULAyVFm+p2NH2QnGNwPRgt04Fj6hxnTLn/M9l6aWlzofGYwwmCGFuEDcfVjW2qNFXtoyGi5ToatFw0WKPQwiViYT2d4sMuLHYX188JWoSgYMQ7vPBDAIOCEB6IvV6tQGGJBvOW2H/QrVPykEA+91OK3yo2pxj9DqQg8biEokwP6STrJTcuY8TDbrsFAg6PgSUReezTCEtVeggBgSMuHtgzTNsfWNjlYDveY4sTyWWB9EV94eFE2jUMjRozhI3QAExM9VXyoZQC7CNLW1T429Ja/2RePTa4oZ+HI6+dJ+d1OBgD64IuYuWE=
