kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgCTOmhAs+giwuRyg2XVZtUDEd1fQh+ycjSVm9z3WHeDY7fblr7XECtZv/PNzYWeYSLdq7z0DsIwCjyh3nlMANga0MR30IF+nNZ3BOlBHQ4ds6I2LWQcAyHUNK0N46tHBSahFYhiP1E9jVnsCWx7AmmzMn9g39yYxZo5S034flhO/U8qbLJgO3xYw7vUDZquvyMFDdExrC5h/F9T6r6C2gMvbvKE96fVQZa7yyYnHv6fv9PnEpiFuEIP/dJhWCpnnvX1TyvSFjtVL9YF9q0uRcDjTFdwftocmT+QwL5E0FR0bwe/zbVKc+8M5bYPEBFP6h/4itaxzZiRKLM/4wvbC4gqGfzrXBhXn2QGB0ToRPR7k/ZtfuR6cN6uKcdfXBfuEnLdQLP17NCRsKS6cgpR0Z/LfeZnj7HBzEyLItTliN6k9XB3JUI+DTMMj+iRlTEZHB4uuH5HWpEBJ7Zk7QJCklTWYP83r5blSGBaOx3qu6k5/QB77YGgLp6nZsa7WfWyLqpj5OPWowhUhQ+zaoqJDK/jPHJAGf8NmVbC8lFnir2Cs61R2JPN5e7n234r9wTKcCMHMvS1VAwNfn1wDOURB2K/W3hxEp9Mm1vHO1Ns+l5ACTLbBe54S7ytIrQr8F9kfrPjWmmjlUYa65OcxJ/VrGI78dqIM6uhiB5Wr4Mz27PHKJhC6Enx8OGjpNNLupUbcRJG3s5lnMZZFwFIrMSkmEd6fySa10OrALSMGpMonjIa7OfGZmzlOCacw/AHmJmeSJJe5Txm8jyn92hiXMbMA0g7AZcO2srVE4ENUrIwSjddk40fqhZ7IPqhpXx4ClWOoQQRX7ftYpM4dHlvtb0eW4GXgKA9JEpWKm80+GemehHzzIbIDt2uyxCa9ZQUXTMyPcBAxoRtfPt4UtCCE2yNwwSS1ImWUWWlyGSTvH9Kkaxa7dIgyDUmbR97ETUsH5sQlAgfDuRY0jP5GQW+massdxe2tIxcfBQtqp5CG3W8qvFDhQSQaLbut/R7wfQI17pxcy87nii2Vy3CNL7UF7MGAV0XlBZMs6/6rBTSxfCcW2RcjUYu0b9ejPTJ8C5Q/p51cgG4+hJo7mVek+3YGzll82sUGMnH8g0XBwl3EMCbGzI8cAGVghOI5sxC0J9jJlAU6u8lM+iAWls0ZEwrO+NDa31uCa30+iR9ILtKLxNwY1/i0F3pWCh5mJhU5VZEpIRVY1kJ5y+3+hdeTbJK0VWJaSIS//2P3cvhh/FmZ1lgAl9yOlN7ukWRzchZr0c1yQWg68V7nRXUqLFoI1F3ksS0kda66PmDJTI5JMoSDdynpTmq9RC2r1JVu/EpmpI04WRq3HnzkPHxFOer2LpPBj+TKTzuNnNqUUG4mfpPnC+pDAX79roViiV56WB38Ahsof5BTCVz0pYZ2b5ydSgOf2l/N4LrHH7Dcsu3C1K3KX+w+CZS/5rYJv3LpCzRovdNgtMfMerh7cJgBWhK92eqxfZjbsu1AOrvNLpXvRkNfgGyFX0maSm9ssg0FWw=
