kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgDF7UY0zmCIdQRSHFQr1NCt1xZRlb5xlC7C6bNt6DX6TkGhra7T0TSBHKwp8ZdrcsmBDLVjT98FO9wILWPIdQE/hEKXSqiLtZDXMxySq9oVrMyXHThaiiDvew3FoQnhJLSPy00J8vJDz2vcxr3UFjrW+ER+36o+JacrZ8Eo+0ELtgK2XAUSSUARL+jJ/SqNrS7rLOdSLEBXjs3YN75vVqYljQExGP+//NONX17j6UpypuRdPQeqDK4T6sufK2y3Ojcz0A19PkifDuuOpbxpFePOOJcmJ/RzuFhbJ7DtAaJxOjgb/Pxfo2iTr+NfH3dChLyxm6A3X7x5CUJJatClWc76u05g01yqWJPlzBw3TMkzbtEjiTIDX4sLbinEDv7MBiBLUJSKAK93zSsYkX7RkCFbJRroHCrxXvpX2nl/wT5V53Ekt4Cmg40sBt/CGXH1Rg0YsPuRYrdgYJ3PABxhCOMZF0nKUtRhmCKFmpHzrblbLhI13Yp/fzihrzMadf+PBpAp70vnZtX8aHrQaN/a3CYcnqpcsaFTk8ZNaBntLmhwTipG5whtznE5vVh2Ov56mYMfyfCjG2EzgjraiXcMOkP1o38Cm3h/n5OvAXSbtGRwhzDHU+n9OQjXRkD51O4CnmskjVqjhhbCOCcgp57Tt7/bgJHn/hlLuuDuAJFhOdIwUGeAZaihrEV9anpYb9lLFQPznJ06u68RWYKeIrHpo/Ku0cdT4sRibTew7NcYIBAvL+Wh/jFQ2ZrsyVBIFPPcEO0YHtXKH4e4SPIJSv7p4n2/MtYEBbFM+QI/DHS0NoJGq+OuaXX3uotJr7Ofnfh4WhkxzbuI7rWZi4qcmeL3i1ep6pFsSf3Tx6PxDfNonuUVmCgn4Ih0Jt9VW4EDhsnFBdR9FM3JKaiUN+vsIa/1SkX8boG+DhcDTTNiuP4V0bcZ0x+Xb3WQNau/vzdHqCPGZzIETiIeRUFGKcuSHP9rOl5Jd4anlX+wgDec6vrLBcg0aQP9l1xQQWgEg7BlVvz8JpgHKcF3ivrQ+EmZcfBerkD6XJoGlmZp7b3RmSItnYriOtgSmLa/t1QxClT5FHJQkP/L+EB63Noc+lBtLUyABF5VAecE3FMfnjia5yRKCb0+PPQc2rGZHvqeeD21RxWMqsvCQBQD/TNJAFrHjCugV6j6+cyXHqGHvSvIV5xmoPmZUmj+NL1vVFOip9mSCAG1KjR1HRAj+bZxMjXXpG55Vm3WN4MfJBshR47uH7UH2emTUr+Rb8trMrsxMpbc5fKmOHlut0/lJfRmilp4vYuEZzoron5SA736hVuReWHR3KXGpQMEQhhtU3opYPnQ4evdqupDZMEUuB9eDCtJ2mWJ/NAvdEU1kJr9lv5wYAebS5hI8hKZXgetN3rBW9DmILAWG3K862JN5t2EZdzSNXeP6oCUjmMhEmc3Mrmsi+rqm0eIh6LuWa7DuPVpMEhioxSNaEopK4cfuwb5CumlsJcaFCLyxl4p2dS7Qu+2xvqxVaBPVoYwGDTnVplA
