kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgCG1zNUAb2rcvXrLr5JK8r8+Z3A3FvYfTvHjxNZSZFSte2eX++BZDnjhbh7YaFRBnI1YzDXPJhTUBeGN24oxAtcOF54/x8uO4v/SJzjJcUdTuul5lo7PM540Frq3JjuSavITyBBhgmO9UUgmd1GuZVvUDDoRruj01sKBqRHaQwNxsqf5HWkXcqDoBqC0qzwzmB17chJS/VD1ueH/nr39Iv3SAUI9zOOl4sCEZe6sSkwdejaxtq5p9JMsr4xKzlYYHHXSbN2FmS7c+1EqkKu3qlbSqiTGekbb0m72uN2zrTLdMGLGF05BODd4MxVMYxIyL/kZIM7l99vOhDcsyK9QaHPBSPYB/sAf1amMpqtghZ2McT9Pq/0XizGUX6uVEI5sdCiO2FoehcXdye/eUOCpP3J8z8yKVBeJL9QUcTdlPCJ6Zn5Z3O5j+hs/D9lD/Rjx7cw7tQsLk1I3+S0tTc6ewPKmUMGw0rykNp2IRsHF74zAsGfMOJLHsZgB9h3lcQMtFJoeJJVI3eahUDOCG3WPJ905wcdLtDeidYJCj4v9iALTuGxoEltFloReN/qXPdMvxcYnhf2rqTqa52GM4Kd5lg7/r3PVHwlz0eG/AEE33efH0+AhzHA1+Zzpfd4p8C/AKEvdh9B/dZzqAV0UKH8DxFp6uVyeSIjLA0XK4E0+Bd5mybN0PeXaHFYweQz6fZVxEN7/mYWWE91TgtJkyvMyqat6PvzYl7KypCpa7bf1dY0lcB50+YcRkPIZA4xn9oZHIRij8unTjr9mvm4ZB9F2+bnPH3KVeLznRIGZ/FrGbR8HHVV48vyzIvpacQllr1SPEZpy9anzN9ruZad3WS8HGlVNGYZx1AsDJ45h7nHnl/snhNVVL0UxKinJbU8jdoor5G25Rw2S1EMkT/14Po1AjiepgqNGqz77XnHmTmngDtIxiP80t5HxhehGVln4jgDRJLyMFyU/Wt/DyWFLe3+tTQpfXYPdX6KCWi1rWsqEMSA9/ppcxtlBaZ9nbqWF865+DyelZyYWeGk6VkMaGmK9p6d6XIfKnwQc2LP6Ru8b3sXsskRpRee6HhAzp+jXHJG8vl8RC8ge6r28kb38OCQsWBRe6Van5AgHetM56/nGUuKILGlc7ls+4gBT99wb20Nxog9vDiirxnF+5yc1mdoCvWZPnpTiPoSO16X2I9UFBInrMpLa+mv70gWin4Sm375/KzC1s4M3sfkjNCSrP2k3QOIRToLxJyrlXKYHPwOfyB19s8JQnk9Jc8qLEnnqZrfUMTq0BvTrmUEioCtddcZX9dzzUvDmfmEL435fO48Vc3O3qx1wcb11ow5DKfnD41DqZLDPN8FhI5TPcrBVk4f4jOP6mpAKMVfA8ZwZb84eJk2uVzT/k2erjDeUczYAi9hH7zLQB5F+AErbwEvsmuKgaKIB5TtHWRUPQFtmMIJkqKhhr9MVRt0Jdi4kp0N/EhfhsvSuTaSy65spoVY6w3yhmntmCxa8c7NJ25s2JO7SQATyELL5MZMYq5aww==
