kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgBec2PJ2bqx2HY9YqtMDmVzUlySaec33oUfQN09RhsMfchidR2KrDRfKHb6otSsU6YfUSZ1c/bcNP+UDOQThZ85TSMoyskKw1ziuOez8sFGRHfIRQqS3M3cXUHEihdrUGQWnR4INVYgThUL39OMtbQRQX+aX5wcal/7AnG6Nmjs7gceDRDMHtU6cn3VAbn8Xm+WNij0gmgLBtAE8FHOvjUBCf7DgCDVRl4kFxffP/I+l46odH3781TAAz9jc2/rfv5HlBJzEtZeB1cuckMXo4RkmFkMMflUcE0L5SMWcYEz34Ci76WgFe964cc7rScvv8ARQU00jHTenYfYJwtjDsRSeaqiBa/7DWgzMt6JWWQkqV0BzBNM/K7LJh3whTGHm1a42jOKN3XrxHDrMWc/V5S/5k+8jVXzDqjntadOY7JyGbgefWmEqhhiNNlHFSSEOlwZhndI9IWp0iHniIGvHjBiKhWKSpG2bD2f6QdzIsMg/o1cp3Eqo57EUTt7EUhuQVEZ4FZuaI1qgXUCZA6XVJy+Cof+q+cgcUyFD4B7822FwmFo3zUq0kbf7/d2X2dn5V57PmKuVEjFBIP8MNIhFmgXnhoa8ow/MmNm2sRyjY17FueNR508q7ROOP4ma8VWbsOTmAVMU+v4mmL+FfovwhGJUOGDbnt0++8CPQITVO0gXRh4P0bUgO0Bko33c+4B4c4da02IxaDQ7jQJIS979jEhk9B5J1wMc+CifyNqhz22PVKP2HskuNiGtKRU/vR5bD/rOy+skF2AogItOu6XDbCQAUG0DzwakszY6BCS4VTbNBitN4VMF4vIG2W9Hb5GTXI2jZKUAmXOrZUnPoP1eoNM7HOsr41lm1WOcCl2lIqpnGhSS6zsg62LeSj/bm82TvedOrU4JC5MnW9gb+qnMjMUDRFlZVpMpYmc1ujtRXIfSMucdcWRiJ0xIPyqMIDs5OYsOjP0qTZDLHNo2jOngQnraJfR3fYcn97unLG15wNRrUwrZpWF8eYBeDoPUQfT2+/1gldYIP2t+F19pKc8fPtjB/Z31ZznN23zHbsnFDEpF6vIvFXQ15PvsktQ1u6JLzs7cJbvhwOOZZ6P09az8FirnqZivER9swrIxjenfgOGptMTGnNLJi6F8zGnypYRHQj69EFjMS8Z6Hkp4Lb/liDCXlA1iu3ew4pH2HM922UcmsTxn+7vxNMpxrrvkS1Qz/OLiTD18klLjgqo5FNWT52PBCiEDjZip7ElBZSh76Akj3YfFeIkqydJrOtmLUUxEj+ublPM3u+Si156JlQDOGd8DGFn3RW6Yif8tL/DmMDTBkhRVhBTutwlJK6VLjPAS7vJhV8CqqAeJkaD3UYcF/7cBvYMghc6QuOdoQWbQa8DgcZ6rcZhglNxUgjaKA/tZYpG4zWOy4+pke26vXHjGwwAMBJ/N9dKCUdEPTuWDclr6ljffSL1Ei+TQzsfqFK1MEKlJ39+AtkQaNpgK+z3L4RmOZVv3WKdN52ar6QYcSnIeuHqN2+22Ak=
