apiVersion: v1
kind: Secret
metadata:
  name: dex-config
  namespace: auth
stringData:
  config.yaml: |
    issuer: https://34.124.196.56
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: debug
      format: text
    oauth2:
      skipApprovalScreen: true
    expiry:
      signingKeys: 4h
      idTokens: 1h
    enablePasswordDB: true
    staticPasswords:
    - email: test@demo.me
      username: test
      hash: $2y$12$rFM4DHFw4fmXZg.VInjQkuY98WvUkDH8/VvDB1B3dpZyH9LnXlpIS
      userID: 56ab82c9-2edd-4fe2-89aa-21fd3e0aa7a4
    staticClients:
    - id: f5adaf0cfffa20bb685168343fbdc8d7
      secret: bf31b4f7cbcdcd96937db71359862a88d02f5b2ac445c0dff80d41513f9c065b
      redirectURIs:
      - https://34.124.196.56/oauth2/callback
      name: Dex Login Application
