kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgAgxSWPm3DHyi3h1WuDX4kcUTcUwSQMZHxaDu1eS4u8p3I2H/S3UBqH3D9zLHFVhN5TUDSEJ22DoIuh2HyHfQTrldCxQxxQrs+k504qBJXZkcJZozemUw6X6nwQ8BHk4xKFo22CMkW2ui8ZeEiV/Im9Wy4AIYdHzXHb+JecNibA5epuz4MS2lhsFSJHj6pJIiOchcXvo21Y2xW1addRi1TV9ruVT9bbRNJm6AkIwUyOuEJVofqF3MCbDgomCap7UXg0M7rqTfo2BW5ESC43Olxly2GuA2z9XUIqvJmAVa0EACP9DFLk/ifVO0pGqQLmYHQHJtH1phHSxTJ2njkEv6Jwrsd+n5gapT+IawJwX54E3J18EvuGWWlXe6yDJy75YlGsbNS1a71+y9Is/7aUIyhJqXCiYmdIt41JWTv2WFrGWTvWzM2CAEJA7P9kxHFUBk3wOWhq3RYVsje2j58d4yqmM0vANtnLLQsN3bm973w4PQ9QgK4oAZx5vZwVyLnLm2hCW0IcoXWghqfQ5NlKQZT+YCnoxbQITK8iN64N9EGuizQLLzoVSoAk/o1NH4fH8VhrPUf7EyWEHW2Kmr0nSBU346XACdoXKTzON+1dJcqA0kKFtbB6CEQv3w5M8VEZPxRCvn9fFCiyxFgYv8xK2ZUlzAazpqBw1ddjbWzFpgOaQeE7cuD6Rxtw/ckbNkPSexsgabRWBzIWyPoZ8Jre42+EfQZ1yP8dLpf0WpHgxOb3t3tOTb0mY3lJft4K6B2mGbSbiX76jB8zbS8VJ856IH3+o+zoRyadFUUBJ/wY5xFzddwNeouu/APGCfFl4JC1gFFPSnduPFcrGgRkC9ldbMKmD58lDLO3vTl9yzOco8eKXYc28xZzhy/1TglEBzmJHHY6RwfoGhUQG7lHgzPEVt8l6FpxTEYqlRBekSBkOecg1QL3ynzGGN2uVAgKocqwRBZld+1CxO/Rx2nb47d9QK6faif+AJhfm3/RxZdjLHHszxfPYjf6GLOVbMcdbKipN1bhgR/BcAPrVE95USe89pOFnv1EL1ZR6Ns2txSawuyS/MZfXUh15WFEnxNDF55ctuVDdTB6lSk3cvS18t+U9B0queAJYvbnuGHORWYV5uKkwXOld8KztkmVbHiKW4qvFw9MBkEu+sJ5FrEfM+wuKCXc3ptE3McelcPiTej26g2Pd4I4via+gOZMkpxWdINXnRTBCNjiyHl0apjz4UwjxYSm5D+dbtq4KHW1twCaH+CsXfHVbY5rrvXYCa03iFED0uuoWnMGVWE+yuG100HXduwmQpRUcRhAdwBKN5eFZv+AkDZ5xwx5/fjQQyYT25UM9sScD0BmFOeTHntduO0Ylbp2fC2uQqCGcA0UPEcoX8iRZSLCCp547n5/ALaqmrL0/jkEecieLZgYH99zb7XelOzZjh4itX0j1oXjsueJ1unKgjRhE9AFos8AMUiu0rqGJ/wJUi5XGkaOGWBrFT5P6Vqo5kNEOXERDtT4JrI/oubYZNX5MI0h+SSj
