kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgBwb26LBr3dELAyCAQnEUqGuLnoid27/sf813XEhx5gDS7bggAVlBbOgjKE0VjzD8nx0fTyhSFn37gir6/EkZ1o2U8AT3OW7pPkL88yYe4XG3BTFlUbbHD65+cAFcRfDLLAzH5d6UP6v70PlWGOEpI+ItVHldQuniHaAacYu3rNOmpMuzPTF+M2DDEukMHjEbqHYzYF7RS5EjIe1HBX9uoXZ9nrZ+o4Sji4kgn/+DbOG6so1xDnngN380GYBtbtBNZYexkrA/sIqfCsK6vz1tN4+5TZ3593C/njLJkx4QrFg0WQH3PUYINQpTJod8u3ygDOIhOpA8qMrXxbSBHT1jf9v3BvimbsATR/YtpItXFCQLq8YYRd+BNBI0UbzIhn3efzadvqiwZZdSn9r1mCn1YCKbEmR4IalZED0KvuouVl8QGP6TWCJhypTDLV/vxb4mOkdYmfqyB606zZLs94V6K37aJ6x8xyCe1X7vq0nXsQI2focWXT8K18Cj8l05QMfkrUIDrHDkH6B+OPn4o9Aes7XXJFwdiHI4cqcdeR7R0pQ/1YUa5FuvXoQ6X6FOzAS7KGujiY3VVmz5kf50tLDA+idtPr+Vxt3jrtjkOP7p7knxbkUYh2MpH4DIdMXOz/hSgCrnZUHcSyFMGTvTYF8YFymCd7V2qDEQM31KuIfahMnEaiuPy1KhD8ejAUqv0KQz7WYyExdf2nLMlYLNJADCtAhMczUgjX6pdbXcEGWOty1bUhMGwcyhgUXhPsFb6tXzFOOhdEkeC2EsKC3LECtikuV/76tmoULCZ4MXVwpRDgJcNiBxDYSMcfLvL875/tc0R84Pr2TIXZZM22AZkzqj+4xLZ8niby8usbIQ6y+ckujOet+MhVNp9zqj1AKov8ijb4Lpd+/cFgtxUfN2OVUR0KLdUE3WYit+ue30EMuxTvf0f8GuipSZ+t2kwH/LiDmSvI+TLpGLZvWtTayhoCor5b/wsO9ESCxzTZih2RYHm6BtGE8mB57QxQY2Aqfo5fxzuM+DYowjpN5ZkPegu5cucTT8x3gQ8Bb8mVLmxs5jCs0b6lnDl5V/zyEI6PHzBmE8RmSq+qd+xtfiTWlKyevdCuQt91uCKItalKLqj7KbZ9Ju1eKxvNCV1bZMeqeXfC4QU1JGNiaSKcX7WPmX1512Sr2pucoSZ5H7GyBt4dj1k7vk7PniJAP+szFNXQTUqZmVVMg3KdF6s36/yjdVMolfsa/dvqsJgzSyqcrrb1rEUqMfpBv7irK/MS1tApzyGh9p2/1EkvnaBRzQHjLivEg+il7V5vdyWnm2Y6E7Vt0aCgp4oTbcl88nS+LO9OTRxFjGHQqBusKskHDEB42rhccRi4iXaFOQ0NV9dyIMsuLwYM9+VJZ7DkJRhseB72spzdl3a3OCHY3625mJ7m93nUs1Gp1WsO5ZxxbSOR0QicHLpV3+kAsBnh1WlQwxXBRcAnqGXq5KEe2DYcHQoU+ylQq/WwC1mPDgk/1za14zo1Roqx8b/uFMlvYdd8
