kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dex-config
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: dex-config
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    config.yaml: AgAQvaMvZxWRQLPXN8YK9PeejGgfEFYA8izmNlt8nLBQaw054Y51snjddMOhKLWSOGF3HFWTwmF+47C1U76k+CfQK/jiAcPitdVal/kqDlh9Usov77CRWxTxiAm8xsxAos0VJ7G5L4zdoYqu4lHj28di7OiSoPyHX8NcLS2ZD9UhlGOgf0oVoB3w0+t9BK1xBe+nedm+Zdpmi2XaxSfkGhgH/OzToe+kxWNpfvLINExp+FlRm6AvDso0c61NKes4cUk/hXNiteWhLjhkcZdHZ9DZ7edhEx6GvFWiEbLtFxRA1ItxfAoUG867guxD7Mk1YMTmjjHeGC1GY/NPowztGBnHbRUyLntgVd0TVNKCl0d9ZdIb8Q6iL3xMFVwrCJNYoDv6EjNt/2bOsklOWIiyLLnTT2XRFMVf/AmjqwfVhqKeGbPPyF1/6TBkmiVQQH6bSj4svAB80UDN3zVui3xJyDhiTyS/qTmIBx/AXm6n8LFwhf4m0hnlwnhKt5Wph9cFhFr5ftSrjL6UH6GMdG81OC98Rjam98lILatW+AjpLrLT6I7i5X1CR0NEoByB1V0xsrxZ4c0fk31TngBqGR2kCxL/mrakKPUgyZmOzj7PB9s5/ieojfdaZbXPPnkAVPjFlW9lsWVcbiMte4GM/YUiAzCKVccH964XOxVe1/2Fz2BLqHyFvJEmBws0swjJ2i1tV0tnPJsGQJHN0AiLS/Ds/yUQFVRW+aGJbN4NTuLEulZifz7ANDBvdtBtR64AnqBL6Lr0Rhs1rDtR2hWjn0+On9eZfAe+rYsbTKZQQa2BHV4ev0ccGTZomSWy2rwwQhDXXAY0892Wkew9kr8F31g7CRD2fwgltN3Sbsj4Gbxlh8kM/OUzMkwJBvdBkGbm4t1YXx2z8QP8SJDS8LP6reHsDXQUllJEpgYZogzsrxKEo5Iwfg0G3/JWAYOWM7fsMtzqqnnqECraKWc/T7z3CbuELpUv2JO07/E5o4ZbQ69Sdt4YqmEo+2cVVZTjvXHlc2xdA5EiiGkScflbj72wFSfE3aP/NCmTWA7jTHzbEyj0Nj3xBSgzhCZd1doL5sZZQq0kvT5ygi5OdNKr5YmLbcTG3Drdpdn3uxAMzj+JxOxiTR9XDREc2kNPtbSslbdFkpZ2SG/jKcBYWgScMwFdAmx8Z3jH51aZOmL63YFC0q6D0o6BZr0i5+L4tTcu113JBjivYKylJvAopC6YSaVTzDGosWtmBXlizZ0iVWPW6jQHQjG8M2caPYiiWNJYcoAY2mdixw+s8kk714KPB50wJ/KfnazCdgBjP2PKeVV95dpc8LD3vR0kRChjgd5KJG5IBqdBBtg6mjQJemDW9akFbHb/n7DRFp1qAhZppGHNub8xdM9N3zpc/RphrROgZwxuKvXSRNbDTBujTG762uOsa4vFS0QpaSo9mfRwfp8H06GE+u5eU4vbpsApMeh5iaLMsZYjpUPp5e4edjADMvb4fa68QqCUphvOEdQN70Gd9gGM7/89XNkpDhT7YNA=
