apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: auth
data:
  client-id: "f5adaf0cfffa20bb685168343fbdc8d7"
  client-secret: "bf31b4f7cbcdcd96937db71359862a88d02f5b2ac445c0dff80d41513f9c065b"
  cookie-secret: "CmkOvqJGHmLvZ1atjx2MAA=="
