apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: panopticon-gateway-certs
  namespace: istio-system
spec:
  secretName: panopticon-gateway-certs
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
  commonName: "*"
  dnsNames:
  - "*"
