apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  spawner_ui_config.yaml: |
    spawnerFormDefaults:
      image:
        value: ghcr.io/pluralsh/kubeflow-notebooks-jupyter-scipy:v1.0.0
        options:
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-scipy:v1.0.0
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-pytorch-full:v1.0.0
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-pytorch-full-cuda:v1.0.0
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-tensorflow-full:v1.0.0
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-tensorflow-full-cuda:v1.0.0
      imageGroupOne:
        value: ghcr.io/pluralsh/kubeflow-notebooks-codeserver-python:v1.0.0
        options:
          - ghcr.io/pluralsh/kubeflow-notebooks-codeserver-python:v1.0.0
      imageGroupTwo:
        value: ghcr.io/pluralsh/kubeflow-notebooks-rstudio-tidyverse:v1.0.0
        options:
          - ghcr.io/pluralsh/kubeflow-notebooks-rstudio-tidyverse:v1.0.0
      allowCustomImage: true
      imagePullPolicy:
        value: IfNotPresent
        readOnly: false
      cpu:
        value: "0.5"
        limitFactor: "1.2"
        readOnly: false
      memory:
        value: 1.0Gi
        limitFactor: "1.2"
        readOnly: false
      environment:
        value: {}
        readOnly: false
      workspaceVolume:
        value:
          type:
            value: New
          name:
            value: 'workspace-{notebook-name}'
          size:
            value: '5Gi'
          mountPath:
            value: /home/jovyan
          accessModes:
            value: ReadWriteOnce
          class:
            value: '{none}'
        readOnly: false
      dataVolumes:
        value: []
        readOnly: false
      gpus:
        value:
          num: "none"
          vendors:
            - limitsKey: "nvidia.com/gpu"
              uiName: "NVIDIA"
            - limitsKey: "amd.com/gpu"
              uiName: "AMD"
          vendor: ""
        readOnly: false
      affinityConfig:
        value: ""
        options: []
      tolerationGroup:
        value: ""
        options: []
        readOnly: false
      shm:
        value: true
        readOnly: false
      configurations:
        value: []
    readOnly: false
