apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dapr.github.io/helm-charts
    targetRevision: 1.7.0
    chart: dapr
    helm:
      parameters:
      - name: global.prometheus.enabled
        value: "false"
      - name: dapr_operator.debug.enabled
        value: "false"
      - name: dapr_operator.livenessProbe.initialDelaySeconds
        value: "5"
      - name: dapr_operator.livenessProbe.periodSeconds
        value: "5"
      - name: dapr_operator.livenessProbe.failureThreshold
        value: "5"
      - name: dapr_placement.debug.enabled
        value: "false"
      - name: dapr_placement.livenessProbe.initialDelaySeconds
        value: "15"
      - name: dapr_placement.livenessProbe.periodSeconds
        value: "5"
      - name: dapr_placement.livenessProbe.failureThreshold
        value: "5"
  destination:
    server: https://kubernetes.default.svc
    namespace: dapr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
