apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dapr.github.io/helm-charts
    targetRevision: 1.5.1
    chart: dapr
    helm:
      parameters:
      - name: global.prometheus.enabled
        value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: dapr-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
