apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphscope
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://graphscope.oss-cn-beijing.aliyuncs.com/charts
    targetRevision: 0.12.0
    chart: graphscope
    helm:
      parameters:
      - name: coordinator.service.resources.requests.memory
        value: 512Mi
      - name: coordinator.service.resources.requests.cpu
        value: 0.5
      - name: engines.resources.requests.memory
        value: 512Mi
      - name: engines.resources.requests.cpu
        value: 0.5
      - name: vineyard.shared_mem
        value: 512Mi
      - name: jupyter.resources.requests.memory
        value: 512Mi
        value: 0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: graphscope-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
