apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphscope
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://graphscope.oss-cn-beijing.aliyuncs.com/charts
    targetRevision: 0.8.0
    chart: graphscope
  destination:
    server: https://kubernetes.default.svc
    namespace: graphscope-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
