apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haoxins/panopticon.git
    targetRevision: deploy
    path: kubeflow/pipelines
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
