apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    chart: oauth2-proxy
    helm:
      parameters:
      - name: image.repository
        value: quay.io/oauth2-proxy/oauth2-proxy
      - name: image.tag
        value: v7.2.0
      - name: configSecret.create
        value: "false"
      - name: config.existingSecret
        value: oauth2-proxy
      - name: service.portNumber
        value: "4180"
      - name: extraArgs.provider
        value: oidc
      - name: extraArgs.set-xauthrequest
        value: "true"
      - name: extraArgs.cookie-secure
        value: "true"
      - name: extraArgs.cookie-samesite
        value: lax
      - name: extraArgs.cookie-refresh
        value: 1h
      - name: extraArgs.cookie-expire
        value: 168h
      - name: extraArgs.cookie-name
        value: _oauth2_proxy
      - name: extraArgs.email-domain
        value: "*"
      - name: extraArgs.upstream
        value: static://200
      - name: extraArgs.skip-provider-button
        value: "true"
      - name: extraArgs.cookie-domain
        # 1. Cookies do not provide isolation by port
        # 2. localhost is not a valid domain
        value: ""
      - name: extraArgs.whitelist-domain
        value: localhost
      - name: extraArgs.oidc-issuer-url
        value: https://localhost
      - name: extraArgs.login-url
        value: /auth
      - name: extraArgs.oidc-jwks-url
        value: /auth/keys
      - name: extraArgs.redeem-url
        value: /auth/token
      - name: extraArgs.scope
        value: openid profile email
      - name: extraArgs.user-id-claim
        value: email
      - name: extraArgs.skip-oidc-discovery
        value: "true"
      - name: extraArgs.ssl-insecure-skip-verify
        value: "false"
      - name: extraArgs.skip-auth-route[0]
        value: /auth
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 5.0.6
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
