apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision:
    path: helm-chart/ray-cluster
    helm:
      parameters:
      # - name:
      #   value:
  destination:
    server: https://kubernetes.default.svc
    namespace: ray-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
