---
# This issuer is used by certain Kubeflow applications
# for cluster-internal certificates.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeflow-self-signing-issuer
spec:
  selfSigned: {}
